
package interfazhorasperros;

import javax.swing.JOptionPane;

/**
 *
 * @author DANIEL BARRANTES
 */

public class InterfazPerros extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPerros
     */
    public InterfazPerros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        num3 = new javax.swing.JTextField();
        num4 = new javax.swing.JTextField();
        result = new javax.swing.JTextField();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("NUMERO DE HORAS DE PASEO Y TAMAÑOS DE PERROS CON EL 10% DE DESCUENTO SI LLEVAS OTRO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 22, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("COSTO DE CADA TAMAÑO DE PERRO QUE PASEA (GRANDES A 10.000) (MEDIANOS A 5.000) (PEQUEÑOS A 3.000)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("CANTIDAD HORAS DE PASEO ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 168, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("CANTIDAD PERROS GRANDES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 283, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("CANTIDAD PERROS MEDIANOS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 374, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("CANTIDAD PERROS PEQUEÑOS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 470, -1, -1));
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 159, 49, 35));
        getContentPane().add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 274, 49, 35));
        getContentPane().add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 365, 49, 35));
        getContentPane().add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 461, 49, 35));
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 560, 84, 35));

        Boton1.setBackground(new java.awt.Color(0, 255, 51));
        Boton1.setForeground(new java.awt.Color(255, 255, 255));
        Boton1.setText("COSTO TOTAL");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 566, -1, -1));

        Boton2.setBackground(new java.awt.Color(255, 0, 0));
        Boton2.setForeground(new java.awt.Color(255, 255, 255));
        Boton2.setText("BORRAR");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 566, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\horasrejo.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 112, -1, 128));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\grande hasta el pequeño.jpeg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 274, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\ojala.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -150, 860, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        // TODO add your handling code here:
        num1.setText("");
        num2.setText("");
        num3.setText("");
        num4.setText("");
        result.setText("");
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
        int TotalTodo = Integer.parseInt(num2.getText()) * 10000 + Integer.parseInt(num3.getText()) * 5000 + Integer.parseInt(num4.getText()) * 3000;
        result.setText(TotalTodo+"");
        JOptionPane.showMessageDialog(null, "Usuario has escrito que vas a pasear :\n" + Integer.parseInt(num2.getText()) + " perros grandes.\n" + Integer.parseInt(num3.getText()) + " perros medianos y \n" + Integer.parseInt(num4.getText()) + " Perros pequeños.\n" + "La suma de los numeros de los perros digitados es de: " + TotalTodo+ " $ Pesos colombianos");

        int horasTotal = TotalTodo * Integer.parseInt(num1.getText());
        int DescuentoPerro = (int) (horasTotal - (horasTotal *0.10));

        if (Integer.parseInt(num2.getText()) + Integer.parseInt(num3.getText()) + Integer.parseInt(num4.getText()) == 1) {
            JOptionPane.showMessageDialog(null, "Usuario has paseado un perro, no se le hara descuento.\n" + "El costo del paseo del perro es de: " + horasTotal+" $ Pesos colombianos");
            result.setText(horasTotal+"");
        }
        if (Integer.parseInt(num2.getText()) + Integer.parseInt(num3.getText()) + Integer.parseInt(num4.getText()) > 1) {
            JOptionPane.showMessageDialog(null, "Usuario has paseado mas de un perro, se le acumulara el descuento del 10%:\n" + "El costo total del paseo de los perros es de: " + DescuentoPerro+" $ Pesos colombianos");
            
            result.setText(DescuentoPerro+"");
    }//GEN-LAST:event_Boton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPerros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPerros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPerros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPerros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPerros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    private javax.swing.JTextField num4;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
